spring.application.name=Gimnasio

# Configuración de la Base de Datos con prefijo 'spring.'
spring.datasource.url=jdbc:mysql://localhost:3306/gimnasio?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración de JPA e Hibernate con prefijo 'spring.'
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect